config/routes.rb
Rails.application.routes.draw do
  # Pages
  root 'pages#home'
  # Carts
  get '/cart', to: 'carts#show', as: 'cart'
  get '/carts/:id', to: 'carts#show'
  post '/carts/:id_product', to: 'carts#add_product', as: 'add_product_to_cart'
  
  namespace :admin do
    get 'categories',           to: 'categories#index', as: 'categories'
    get 'categories/new',       to: 'categories#new',   as: 'new_category'
    get 'categories/:id',       to: 'categories#show',  as: 'category'
    get 'categories/:id/edit',  to: 'categories#edit',  as: 'edit_category'
    post    'categories',         to: 'categories#create'
    put     'categories/:id',     to: 'categories#update'
    patch   'categories/:id',     to: 'categories#update'
    delete  'categories/:id',     to: 'categories#destroy'
    get 'roles',          to: 'roles#index',    as: 'roles'
    get 'roles/new',      to: 'roles#new',      as: 'new_role'
    get 'roles/:id',      to: 'roles#show',     as: 'role'
    get 'roles/:id/edit', to: 'roles#edit',     as: 'edit_role'
    post    'roles',          to: 'roles#create'
    put     'roles/:id',      to: 'roles#update'
    patch   'roles/:id',      to: 'roles#update'
    delete  'roles/:id',      to: 'roles#destroy'    
    get 'statuses',             to: 'statuses#index',   as: 'statuses'
    get 'statuses/new',         to: 'statuses#new',     as: 'new_status'
    get 'statuses/:id',         to: 'statuses#show',    as: 'status'
    get 'statuses/:id/edit',    to: 'statuses#edit',    as: 'edit_status'
    post    'statuses',            to: 'statuses#create'
    put     'statuses/:id',        to: 'statuses#update'
    patch   'statuses/:id',        to: 'statuses#update'
    delete  'statuses/:id',        to: 'statuses#destroy'    
    get 'products',             to: 'products#index', as: 'products'
    get 'products/new',         to: 'products#new',   as: 'new_product'
    get 'products/:id',         to: 'products#show',  as: 'product'
    get 'products/:id/edit',    to: 'products#edit',  as: 'edit_product'
    post    'products',           to: 'products#create'
    put     'products/:id',       to: 'products#update'
    patch   'products/:id',       to: 'products#update'
    delete  'products/:id',       to: 'products#destroy'
  end
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :cart_products
  has_many :products, through: :cart_products

  validates :total, presence: true, numericality: true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  after_save :calculate_total

  belongs_to :cart
  belongs_to :product

  validates :cart_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true, numericality: true

  private
  def calculate_total
      total = 0
      self.cart.cart_products.each do |cp|
        total += cp.quantity * cp.product.price
      end      
      self.cart.total = total   # Asignar el valor al cart
      self.cart.save            # Guardar el cambio
  end

end

app/models/category.rb
class Category < ApplicationRecord

    before_validation :to_downcase

    has_many :products

    validates :name, presence: true, uniqueness: true

    private
    def to_downcase
        if self.name
            self.name = self.name.downcase
        end
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :status
  has_many :order_details
  has_many :products, through: :order_details
  
  # todo: revisar generación del número del pedido
  validates :number, presence: true, numericality: true, uniqueness: true
  validates :total, presence: true, numericality: true
  validates :status_id, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :order_id,    presence: true
  validates :product_id,  presence: true
  validates :quantity,    presence: true, numericality: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :cart_products
  has_many :carts, through: :cart_products

  has_one_attached :main_photo
  has_many_attached :detail_photos

  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  validates :category_id, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users

    validates :name, presence: true, uniqueness: true
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :orders

    validates :description, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :role
  has_many :orders

  validates :username, presence: true, uniqueness: true
  validates :role_id, presence: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  layout "admin_layout"  
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  def index
    #@products = Product.all # problema n+1
    @products = Product.includes(:category)
  end
  
  def new
    @product = Product.new
    set_categories
  end

  def show
  end

  def edit
    set_categories
  end

  def create
    @product = Product.new(params_product)
    if @product.save
      redirect_to admin_products_path
    else
      set_categories
      render :new
    end
  end

  def update
    if @product.update(params_product)
      redirect_to admin_products_path
    else
      set_categories
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to admin_products_path

  end

  private
  def set_product
    @product = Product.find(params[:id])
  rescue
    flash[:set_product_error] = "Could not find the record #{params[:id]}"
    redirect_to admin_products_path
  end

  def params_product
    params.require(:product).permit(:name, :price, :description, :category_id, :main_photo, detail_photos: [])
  end

  def set_categories
    @categories = Category.all
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  include PagesHelper
  before_action :set_cart_from_cookies # nos asginar la variable @cart

  def show
  end

  # POST /carts/:id_product
  def add_product
    # recuperar el id de cart -> cookie
    # recuperar el id del product
    # guardar el registro en CartProduct
    cart_product = CartProduct.new
    cart_product.cart = @cart
    cart_product.product_id = params[:id_product]
    cart_product.quantity = 1
    cart_product.save

    flash[:cart_product_created] = "Product added"
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  include PagesHelper
  before_action :set_cart_from_cookies

  def home  
    @products = Product.includes(:category).shuffle
    OrderMailer.with(product: Product.first).send_mail.deliver_later
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/cart_products_helper.rb
module CartProductsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
def cookies_handler
    
end

def print_icon
  puts "🖨".center(50,"-")
  
end

def set_cart_from_cookies

    if cookies[:cart_id]
      @cart = Cart.find(cookies[:cart_id])
     else
      @cart = Cart.create(total: 0)
      cookies[:cart_id] = @cart.id
    end
   
  
end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/products/_form.html.erb
<!-- VARIABLES: base_product ; categories -->

<div class="card">
    <div class="card-body">
        <%= form_with(model: [:admin, base_product]) do |form| %>
            <div class="mb-3">
                <%= form.label      :name, class: 'form-label' %>
                <%= form.text_field :name, class: 'form-control' %>
                <% if base_product.errors[:name].any? %>
                    <div>
                        <%= base_product.errors[:name].first %>
                    </div>
                <% end %>
            </div>
            <div class="mb-3">
                <%= form.label      :price, class: 'form-label' %>
                <%= form.text_field :price, class: 'form-control' %>
                <% if base_product.errors[:price].any? %>
                    <div>
                        <%= base_product.errors[:price].first %>
                    </div>
                <% end %>
            </div>
            <div class="mb-3">
                <%= form.label      :description, class: 'form-label' %>
                <%= form.text_field :description, class: 'form-control' %>
                <% if base_product.errors[:description].any? %>
                    <div>
                        <%= base_product.errors[:description].first %>
                    </div>
                <% end %>
            </div>
            <div class="mb-3">
                <%= form.label  :category_id, class: 'form-label' %>
                <%= form.select :category_id, 
                options_from_collection_for_select(@categories, :id, :name, base_product.category_id),
                { include_blank: "Select a category" }, 
                {class: 'form-control'} %>
                <% if base_product.errors[:category_id].any? %>
                    <div>
                        <%= base_product.errors[:category_id].first %>
                    </div>
                <% end %>
            </div>

            <div class="mb-3">
                <%= form.label :main_photo, class: 'form-label' %>
                <%= form.file_field :main_photo, class: 'form-control' %>
            </div>

            <div class="mb-3">
                <%= form.label :detail_photos, class: 'form-label' %>
                <%= form.file_field :detail_photos, multiple: true, class: 'form-control' %>
            </div>

            <%= form.submit class: 'btn btn-primary' %>
        <% end %>
    </div>
</div>

app/views/admin/products/edit.html.erb
<h3>Edit Product</h3>
<%= render 'form', base_product: @product, categories: @categories %>
<i class="fas fa-arrow-circle-left" ></i>
<%= link_to 'back', admin_products_path, class:"btn btn-secondary text-white" %>

app/views/admin/products/index.html.erb
<h3>Products</h3>

<div class="card">
    <div class="card-body">
        <h5> Index </h5>
        <%= link_to "New", admin_new_product_path, class: 'btn btn-primary' %>

        <% if flash[:set_product_error] %>
            <%= flash[:set_product_error] %>
        <% end %>

        <table class="table table-hover">
            <tr>
                <th> Name </th>
                <th> Price </th>
                <th> Description </th>
                <th> Category </th>
                <th> Action </th>
            </tr>
            <% @products.each do |p| %>
                <tr>
                    <td> <%= link_to admin_product_path(p) do %>
                        <%= p.name %>
                       <%end%></td>
                    <td> <%= number_to_currency(p.price,  unit: 'CLP $ ', delimiter: '.', precision: 0) %> </td>
                    <td> <%= p.description  %> </td>
                    <td> <%= p.category.name  %> </td>
                    <td>
                        <%= link_to "Edit", admin_edit_product_path(p), class: 'btn btn-warning'  %>
                        <%= link_to "Delete", admin_product_path(p), class: 'btn btn-warning', method: :delete, data: { confirm: "Are you sure?" }  %>
                    </td>
                </tr>
            <% end %>
        </table>
    </div>
</div>

app/views/admin/products/new.html.erb
<h3>New Product</h3>

<%= render 'form', base_product: @product, categories: @categories %>
<i class="fas fa-arrow-circle-left" ></i>
<%= link_to 'back', admin_products_path, class:"btn btn-secondary text-white" %>

app/views/admin/products/show.html.erb
<h3>Show Product</h3>

<h4>ID <%= @product.id %></h4>
<h2>Product: <%= @product.name %></h2>
<h3>Price: <%= @product.price %></h3>
<h4>Description: <%= @product.description %></h4>
<h4>Category: <%= @product.category.name %></h4>
<% if @product.main_photo.attached? %>
          <%= image_tag @product.main_photo, class:"rounded card-img-top shadow-sm", style:"max-height:10rem; max-width:10rem;" %>
            <% end %>
            <br><br>
<%= link_to 'back', admin_products_path, class:"btn btn-secondary" %>