config/routes.rb
Rails.application.routes.draw do
  # Pages
  root 'pages#home'
  # Carts
  get '/cart', to: 'carts#show', as: 'cart'
  get '/carts/:id', to: 'carts#show'
  post '/carts/:id_product', to: 'carts#add_product', as: 'add_product_to_cart'
  
  namespace :admin do
    get 'categories',           to: 'categories#index', as: 'categories'
    get 'categories/new',       to: 'categories#new',   as: 'new_category'
    get 'categories/:id',       to: 'categories#show',  as: 'category'
    get 'categories/:id/edit',  to: 'categories#edit',  as: 'edit_category'
    post    'categories',         to: 'categories#create'
    put     'categories/:id',     to: 'categories#update'
    patch   'categories/:id',     to: 'categories#update'
    delete  'categories/:id',     to: 'categories#destroy'
    get 'roles',          to: 'roles#index',    as: 'roles'
    get 'roles/new',      to: 'roles#new',      as: 'new_role'
    get 'roles/:id',      to: 'roles#show',     as: 'role'
    get 'roles/:id/edit', to: 'roles#edit',     as: 'edit_role'
    post    'roles',          to: 'roles#create'
    put     'roles/:id',      to: 'roles#update'
    patch   'roles/:id',      to: 'roles#update'
    delete  'roles/:id',      to: 'roles#destroy'    
    get 'statuses',             to: 'statuses#index',   as: 'statuses'
    get 'statuses/new',         to: 'statuses#new',     as: 'new_status'
    get 'statuses/:id',         to: 'statuses#show',    as: 'status'
    get 'statuses/:id/edit',    to: 'statuses#edit',    as: 'edit_status'
    post    'statuses',            to: 'statuses#create'
    put     'statuses/:id',        to: 'statuses#update'
    patch   'statuses/:id',        to: 'statuses#update'
    delete  'statuses/:id',        to: 'statuses#destroy'    
    get 'products',             to: 'products#index', as: 'products'
    get 'products/new',         to: 'products#new',   as: 'new_product'
    get 'products/:id',         to: 'products#show',  as: 'product'
    get 'products/:id/edit',    to: 'products#edit',  as: 'edit_product'
    post    'products',           to: 'products#create'
    put     'products/:id',       to: 'products#update'
    patch   'products/:id',       to: 'products#update'
    delete  'products/:id',       to: 'products#destroy'
  end
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :cart_products
  has_many :products, through: :cart_products

  validates :total, presence: true, numericality: true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  after_save :calculate_total

  belongs_to :cart
  belongs_to :product

  validates :cart_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true, numericality: true

  private
  def calculate_total
      total = 0
      self.cart.cart_products.each do |cp|
        total += cp.quantity * cp.product.price
      end      
      self.cart.total = total   # Asignar el valor al cart
      self.cart.save            # Guardar el cambio
  end

end

app/models/category.rb
class Category < ApplicationRecord

    before_validation :to_downcase

    has_many :products

    validates :name, presence: true, uniqueness: true

    private
    def to_downcase
        if self.name
            self.name = self.name.downcase
        end
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :status
  has_many :order_details
  has_many :products, through: :order_details
  
  # todo: revisar generación del número del pedido
  validates :number, presence: true, numericality: true, uniqueness: true
  validates :total, presence: true, numericality: true
  validates :status_id, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :order_id,    presence: true
  validates :product_id,  presence: true
  validates :quantity,    presence: true, numericality: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :cart_products
  has_many :carts, through: :cart_products

  has_one_attached :main_photo
  has_many_attached :detail_photos

  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  validates :category_id, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users

    validates :name, presence: true, uniqueness: true
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :orders

    validates :description, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :role
  has_many :orders

  validates :username, presence: true, uniqueness: true
  validates :role_id, presence: true
end

app/controllers/admin/statuses_controller.rb
class Admin::StatusesController < ApplicationController

    layout 'admin_layout'
    before_action :set_status, only: [:show, :edit, :update, :destroy]
  
    def index
      @statuses = Status.all
    end
  
    def new
      @status = Status.new
    end
  
    def show
    end
  
    def edit
    end
  
    def create
      @status = Status.new(params_status)
      if @status.save
        redirect_to admin_statuses_path
      else
        render :new
      end
    end
  
    def update
      if @status.update(params_status)
        redirect_to admin_statuses_path
      else
        render :edit
      end
    end
  
    def destroy
      @status.destroy
      redirect_to admin_statuses_path
    end
    private
  
    def params_status
      params.require(:status).permit(:description)
    end
  
    def set_status
      @status = Status.find(params[:id])
    rescue
      flash[:set_status_error] = "Could not find the record #{params[:id]}"
      redirect_to admin_statuses_path
    end
  end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  include PagesHelper
  before_action :set_cart_from_cookies # nos asginar la variable @cart

  def show
  end

  # POST /carts/:id_product
  def add_product
    # recuperar el id de cart -> cookie
    # recuperar el id del product
    # guardar el registro en CartProduct
    cart_product = CartProduct.new
    cart_product.cart = @cart
    cart_product.product_id = params[:id_product]
    cart_product.quantity = 1
    cart_product.save

    flash[:cart_product_created] = "Product added"
    redirect_to root_path
  end

end

app/helpers/admin/statuses_helper.rb
module Admin::StatusesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
def cookies_handler
    
end

def print_icon
  puts "🖨".center(50,"-")
  
end

def set_cart_from_cookies

    if cookies[:cart_id]
      @cart = Cart.find(cookies[:cart_id])
     else
      @cart = Cart.create(total: 0)
      cookies[:cart_id] = @cart.id
    end
   
  
end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/statuses/_form.html.erb
<div class="card mb-3">
<div class="card-body">
<%= form_with(model: [:admin, base_status]) do |form| %>
   <div class="mb-3">
    <%= form.label        :description, class:"form-label" %>
    <%= form.text_field   :description, class:"form-control" %>
    <% if base_status.errors[:description].any?%>
    <div class="alert alert-danger" status="alert">
        <%= base_status.errors[:description].first %>
        </div>
        <%end%>
        </div>
    <%= form.submit class: 'btn btn-primary text-white' %>
<% end %>
</div>
</div>
<br>

app/views/admin/statuses/edit.html.erb
<h3>Edit Status</h3>
<%= render 'form', base_status: @status %>
<i class="fas fa-arrow-circle-left" ></i>
<%= link_to 'back', admin_statuses_path, class:"btn btn-secondary text-white" %>

app/views/admin/statuses/index.html.erb
<h3>Statuses</h3>

<div class="card">
<div class="card-body">
<h5 class="card-title">Index</h5>
<%= link_to admin_new_status_path, class:"btn btn-primary text-white" do%>
New <i class="bi bi-arrow-right-circle-fill"></i>
<%end%>
<table class="table table-hover">
    <tr>
        <th >ID</th>
        <th class="text-center">Description</th>
        <th class="text-end">Actions</th>
    </tr>

    <% @statuses.each do |status| %>
        <tr>
            <td style="width:50px;"> <%= status.id %> </td>
            <td class="text-center"> 
            <%= link_to admin_status_path(status) do %>
             <%= status.description %>
            <%end%>
            </td>
            <td class="text-end">
                <%= link_to admin_status_path(status), class: "btn btn-danger text-white", method: :delete, data: { confirm: 'Do you want to delete current record?'} do %>
                <i class="bi bi-trash"></i> Delete
            <% end %>
            <%= link_to admin_edit_status_path(status), class: "btn btn-warning text-white" do %>
            <i class="bi bi-pencil-square"></i> Edit
            <%end%>
            </td>
        </tr>
    <% end %>
</table>
<% if flash[:set_status_error] %>
<%= flash[:set_status_error] %>
</div>
</div>
<%end%>

app/views/admin/statuses/new.html.erb
<h3>New Status</h3>

<%= render 'form', base_status: @status %>
<i class="fas fa-arrow-circle-left" ></i>
<%= link_to 'back', admin_statuses_path, class:"btn btn-secondary text-white" %>

app/views/admin/statuses/show.html.erb
<h3>Show Status</h3>

<h4>ID <%= @status.id %></h4>
<h1>Status: <%= @status.description %></h1>
<%= link_to 'back', admin_statuses_path, class:"btn btn-secondary" %>