config/routes.rb
Rails.application.routes.draw do
  # Pages
  root 'pages#home'
  # Carts
  get '/cart', to: 'carts#show', as: 'cart'
  get '/carts/:id', to: 'carts#show'
  post '/carts/:id_product', to: 'carts#add_product', as: 'add_product_to_cart'
  
  namespace :admin do
    get 'categories',           to: 'categories#index', as: 'categories'
    get 'categories/new',       to: 'categories#new',   as: 'new_category'
    get 'categories/:id',       to: 'categories#show',  as: 'category'
    get 'categories/:id/edit',  to: 'categories#edit',  as: 'edit_category'
    post    'categories',         to: 'categories#create'
    put     'categories/:id',     to: 'categories#update'
    patch   'categories/:id',     to: 'categories#update'
    delete  'categories/:id',     to: 'categories#destroy'
    get 'roles',          to: 'roles#index',    as: 'roles'
    get 'roles/new',      to: 'roles#new',      as: 'new_role'
    get 'roles/:id',      to: 'roles#show',     as: 'role'
    get 'roles/:id/edit', to: 'roles#edit',     as: 'edit_role'
    post    'roles',          to: 'roles#create'
    put     'roles/:id',      to: 'roles#update'
    patch   'roles/:id',      to: 'roles#update'
    delete  'roles/:id',      to: 'roles#destroy'    
    get 'statuses',             to: 'statuses#index',   as: 'statuses'
    get 'statuses/new',         to: 'statuses#new',     as: 'new_status'
    get 'statuses/:id',         to: 'statuses#show',    as: 'status'
    get 'statuses/:id/edit',    to: 'statuses#edit',    as: 'edit_status'
    post    'statuses',            to: 'statuses#create'
    put     'statuses/:id',        to: 'statuses#update'
    patch   'statuses/:id',        to: 'statuses#update'
    delete  'statuses/:id',        to: 'statuses#destroy'    
    get 'products',             to: 'products#index', as: 'products'
    get 'products/new',         to: 'products#new',   as: 'new_product'
    get 'products/:id',         to: 'products#show',  as: 'product'
    get 'products/:id/edit',    to: 'products#edit',  as: 'edit_product'
    post    'products',           to: 'products#create'
    put     'products/:id',       to: 'products#update'
    patch   'products/:id',       to: 'products#update'
    delete  'products/:id',       to: 'products#destroy'
  end
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  has_many :cart_products
  has_many :products, through: :cart_products

  validates :total, presence: true, numericality: true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  after_save :calculate_total

  belongs_to :cart
  belongs_to :product

  validates :cart_id, presence: true
  validates :product_id, presence: true
  validates :quantity, presence: true, numericality: true

  private
  def calculate_total
      total = 0
      self.cart.cart_products.each do |cp|
        total += cp.quantity * cp.product.price
      end      
      self.cart.total = total   # Asignar el valor al cart
      self.cart.save            # Guardar el cambio
  end

end

app/models/category.rb
class Category < ApplicationRecord

    before_validation :to_downcase

    has_many :products

    validates :name, presence: true, uniqueness: true

    private
    def to_downcase
        if self.name
            self.name = self.name.downcase
        end
    end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :status
  has_many :order_details
  has_many :products, through: :order_details
  
  # todo: revisar generación del número del pedido
  validates :number, presence: true, numericality: true, uniqueness: true
  validates :total, presence: true, numericality: true
  validates :status_id, presence: true
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :product

  validates :order_id,    presence: true
  validates :product_id,  presence: true
  validates :quantity,    presence: true, numericality: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :cart_products
  has_many :carts, through: :cart_products

  has_one_attached :main_photo
  has_many_attached :detail_photos

  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :description, presence: true
  validates :category_id, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users

    validates :name, presence: true, uniqueness: true
end

app/models/status.rb
class Status < ApplicationRecord
    has_many :orders

    validates :description, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  belongs_to :role
  has_many :orders

  validates :username, presence: true, uniqueness: true
  validates :role_id, presence: true
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  include PagesHelper
  before_action :set_cart_from_cookies # nos asginar la variable @cart

  def show
  end

  # POST /carts/:id_product
  def add_product
    # recuperar el id de cart -> cookie
    # recuperar el id del product
    # guardar el registro en CartProduct
    cart_product = CartProduct.new
    cart_product.cart = @cart
    cart_product.product_id = params[:id_product]
    cart_product.quantity = 1
    cart_product.save

    flash[:cart_product_created] = "Product added"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
def cookies_handler
    
end

def print_icon
  puts "🖨".center(50,"-")
  
end

def set_cart_from_cookies

    if cookies[:cart_id]
      @cart = Cart.find(cookies[:cart_id])
     else
      @cart = Cart.create(total: 0)
      cookies[:cart_id] = @cart.id
    end
   
  
end



end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/status_helper.rb
module StatusHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_horizontal_menu.html.erb
<div class="container">
    <header class="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom bg-light">
      <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-decoration-none">
        <svg class="bi me-2" width="40" height="32"></svg>
        <span class="fs-4" ><%= image_tag("santa-josefina-logo-2.png", height:"100") %> </span>
      </a>

      <ul class="nav nav-pills">
        <li class="nav-item"><a href="/" class="nav-link text-dark"><i class="bi bi-house"></i> Home</a></li>
        <%= link_to admin_products_path, class:"nav-link text-dark" do %>
        <i class="bi bi-boxes"></i> Products</a></li><% end %>
        <li class="nav-item"><a href="#" class="nav-link text-dark"><i class="bi bi-person"></i> User</a></li>
        <li class="nav-item"><a href="#" class="nav-link text-dark"><i class="bi bi-info-circle"></i> About</a></li>
      </ul>
      <span class="badge bg-light rounded-pill bg-secondary text-dark position-relative">
  <h5><%= link_to cart_path do %> <i class="bi bi-cart4"></i> cart </h5>
  <span class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger">
    <%= @cart.cart_products.count %>
    <span class="visually-hidden">Products in cart</span>
    <%end%>
  </span>
</span>
    </header>
  </div>

app/views/layouts/_vertical_menu.html.erb
 <!-- Sidebar -->
 <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
      </div>
      <div class="sidebar-brand-text mx-2">admin panel <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <%= link_to root_path, class:"nav-link active" do %>
    <i class="bi bi-house-fill"></i>
    Home
  <%end%>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
     Módulos
  </div>

  <!-- Nav Item - Categories -->
  <li class="nav-item">
    <%= link_to admin_categories_path, class:"nav-link text-white" do %>
    <i class="bi bi-tags-fill"></i>
  Categories
  <%end%>
  </li>

  <!-- Nav Item - Roles -->
  <li class="nav-item">
  <%= link_to admin_roles_path, class:"nav-link text-white" do %>
    <i class="bi bi-person-rolodex"></i>
    Roles
  <%end%>
  </li>

  <!-- Nav Item - Products -->
  <li class="nav-item">
  <%= link_to admin_products_path, class:"nav-link text-white" do %>
    <i class="bi bi-boombox-fill"></i>
    Products
  <%end%>
  </li>

  <!-- NAV Item - Statuses -->
  <li class="nav-item">
  <%= link_to admin_statuses_path, class:"nav-link text-white" do %>
   <i class="bi bi-arrows-fullscreen"></i>
    Statuses
  <%end%>
  </li>

  
  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  
</ul>
<!-- End of Sidebar -->
    

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_tag %>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
<link rel=“stylesheet” href=“https://cdn.jsdelivr.net/npm/fontisto@v3.0.4/css/fontisto/fontisto.min.css”>
<link href="sb-admin-2.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
<script src="https://kit.fontawesome.com/19ecb226ec.js" crossorigin="anonymous"></script>
</head>
<body id="page-top">
<!--<div class="container">-->
    <div id="wrapper">  
        <div><%= render "layouts/vertical_menu" %>
</div>
<div id="content-wrapper" class="d-flex flex-column">
    <!-- Main Content -->
    <div id="content">
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <h2 >  
        <i class="bi bi-shop"></i> byMAC Shop :: Admin Panel </h2><i class="fi fi-rails"></i>
    <ul class="navbar-nav ml-auto">
       
        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
       

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 12, 2019</div>
                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 7, 2019</div>
                        $290.29 has been deposited into your account!
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-warning">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 2, 2019</div>
                        Spending Alert: We've noticed unusually high spending for your account.
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li>
       
        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_1.svg"
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                            problem I've been having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_2.svg"
                            alt="...">
                        <div class="status-indicator"></div>
                    </div>
                    <div>
                        <div class="text-truncate">I have the photos that you ordered last month, how
                            would you like them sent to you?</div>
                        <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_3.svg"
                            alt="...">
                        <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Last month's report looks great, I am very happy with
                            the progress so far, keep up the good work!</div>
                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                            told me that people say this to all dogs, even if they aren't good...</div>
                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
        <br>
        <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-info text-decoration-none dropdown-toggle" id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <img src="https://avatars.githubusercontent.com/u/61596615?v=4" alt="" width="25" height="25" class="rounded-circle me-2">
          <strong>byMAC</strong>
        </a>
      </div>
        </li>
    </ul>

</nav>
<!-- End of Topbar -->

   <%= yield %>
 </div>

  <!-- Footer -->
  <footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2021</span> | 
            <i class="fab fa-apple"></i> Mac made
        </div>
    </div>
</footer>
<!-- End of Footer -->  
</div>
</div>

<!--</div>-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script></body>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_tag %>
  <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.0/font/bootstrap-icons.css">
    <link rel=“stylesheet” href=“https://cdn.jsdelivr.net/npm/fontisto@v3.0.4/css/fontisto/fontisto.min.css”>
    <script src="https://kit.fontawesome.com/19ecb226ec.js" crossorigin="anonymous"></script>
  </head>

  <body class="bg-light">
    <%= render "layouts/horizontal_menu" %>
    <div class="container mt-5 pt-5">
      <%= yield %>
    </div>
   <div class="footer"><div class="container"><i class="fab fa-apple"></i> Mac made, <i class="fab fa-aws"></i> Hosted</div></div>
  <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script></body>
</html>

app/views/pages/_card_product.html.erb
<!-- VARIABLES: base_product -->
<div class="row"><div class="col">
  <div class="card  mb-4 rounded shadow-sm " style="height:35rem;">
    <div class="card-header py-3">
          <% if base_product.main_photo.attached? %>
          <%= image_tag base_product.main_photo, class:"rounded card-img-top shadow-sm", style:"max-height:10rem;" %>
            <% end %>
            <h4 class="my-0 fw-normal"><%= base_product.name %></h4>
            <h6 class="text-muted">
            <%= base_product.category.name %>
        </h6>
    </div>
          <div class="card-body">
            <h1 class="card-title pricing-card-title"><%= number_to_currency(base_product.price,  unit: 'CLP $ ', delimiter: '.', precision: 0) %> 
            </h1>
            <%= base_product.description %>
            </div>
            <div class="card-footer">
            <%= link_to add_product_to_cart_path(base_product), method: :post, class:'w-100 btn btn-lg btn-outline-success' , data: { confirm: '¿desea agregar el producto?' } do %>
            <i class="bi bi-cart-plus"></i> Agregar al carro
            <% end %>
          </div>
        </div>
  </div>
</div>

app/views/pages/_product_card.html.erb
<!-- VARIABLES: base_product -->
<div class="row"><div class="col">
  <div class="card  mb-4 rounded shadow-sm " style="height:35rem;">
    <div class="card-header py-3">
          <% if base_product.main_photo.attached? %>
          <%= image_tag base_product.main_photo, class:"rounded card-img-top shadow-sm", style:"max-height:10rem;" %>
            <% end %>
            <h4 class="my-0 fw-normal"><%= base_product.name %></h4>
            <h6 class="text-muted">
            <%= base_product.category.name %>
        </h6>
    </div>
          <div class="card-body">
            <h2 class="card-title pricing-card-title text-primary"><%= number_to_currency(base_product.price,  unit: 'CLP $ ', delimiter: '.', precision: 0) %> 
            </h2>
            <%= base_product.description %>
            </div>
            <div class="card-footer">
            <%= link_to add_product_to_cart_path(base_product), method: :post, class:'w-100 btn btn-lg btn-outline-success' , data: { confirm: '¿desea agregar el producto?' } do %>
            <i class="bi bi-cart-plus"></i> Agregar al carro
            <% end %>
          </div>
        </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row">
    <% @products.each do |p| %>    
        <div class="col-3 mb-3">
            <%= render 'product_card', base_product: p %>
        </div>
    <% end %>
</div>